# Generated by Django 4.1 on 2022-08-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='eid',
            new_name='bid',
        ),
    ]
